# docker compose --profile dev up -d
services:
  db:
    image: mysql:8.0
    container_name: mypicday-mysql
    ports:
      - "9913:3306" # MySQL 포트를 환경 변수로 관리
    profiles:
      - "dev"
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: mypicday
    volumes:
      - mypicday-data:/var/lib/mysql
    networks:
      - mypicday-network
  web:
    image: mypicday:latest
    container_name: mypicday-web
    ports:
      - "8080:8080" # 웹 포트를 환경 변수로 관리
    profiles:
      - "prod"
    environment:
      PROFILE: prod
      PROD_DB_URL: ${PROD_DB_URL}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      JWT_KET: ${JWT_KET}
    depends_on:
      - prod-db
    networks:
      - mypicday-network

  prod-db:
    image: mysql:8.0
    container_name: mypicday2-mysql
    ports:
      - "9914:3306" # MySQL 포트를 환경 변수로 관리
    profiles:
      - "prod"
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_DB_PASSWORD}
      MYSQL_DATABASE: mypicday
    volumes:
      - mypicday-data:/var/lib/mysql
    networks:
      - mypicday-network

volumes:
  mypicday-data:

networks:
  mypicday-network:
    driver: bridge