# docker compose --profile dev up -d
services:
  db:
    image: mysql:8.0
    container_name: mypicday-mysql
    ports:
      - "9913:3306" # MySQL 포트를 환경 변수로 관리
    profiles:
      - "dev"
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: mypicday
    volumes:
      - mypicday-data:/var/lib/mysql
    networks:
      - mypicday-network

volumes:
  mypicday-data:

networks:
  mypicday-network:
    driver: bridge